name = lifesteal_mod
description = Kill players, steal their hearts. If you die, you lose a heart.
depends = flow
optional_depends = default, hudbars, vl_hudbars, mcl_mobitems, mcl_nether, mcl_totems, mcl_potions, mcl_lanterns
supported_games = minetest_game, mineclone2
unsupported_games = mineclonia