name = lifesteal_mod
description = Kill players, steal their hearts. If you die, you lose a heart.
depends = flow
optional_depends = default, hudbars, vl_hudbars, mcl_core, mcl_potions
supported_games = minetest_game, mineclone2
unsupported_games = mineclonia